=== JohanSpaedtke/video-metadata-api/src/main/xsd/material.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://video-metadata.tv.se/material/v1" xmlns:common="http://video-metadata.tv.se/common/v1"
	targetNamespace="http://video-metadata.tv.se/material/v1" version="1.0"
>
	<xs:import namespace="http://video-metadata.tv.se/common/v1" schemaLocation="common.xsd" />
	<!-- 
	 -->
	<xs:element name="material" type="materialType">
		<xs:annotation>
			<xs:documentation>Root element for material object</xs:documentation>
		</xs:annotation>
	</xs:element>
	<!-- 
	 -->
	<xs:complexType name="materialType">
		<xs:sequence>
			<xs:element name="providerId" type="common:idType">
				<xs:annotation>
					<xs:documentation>id for the provider, could be for example 'cmore', 'mtv' or 'se.tv4'
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="id" type="common:idType">
				<xs:annotation>
					<xs:documentation>unique id for content, should include provider name
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="materialType" type="materialTypeType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>type of material
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="distributor" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name of the distributor of the material, legal entity.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="priceGroup" type="priceGroupType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="contentIdRef" type="common:idType"> <!-- todo - same as in content!!! -->
				<xs:annotation>
					<xs:documentation>reference to content</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="videoFormat" type="videoFormatType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>format for video, for example HD
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="audioList" type="audioListType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>list of available audio for this material
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="aspectRatio" type="aspectRatioType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>aspect ratio for the material</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="subtitleList" type="subtitleListType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>list of available subtitles</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="accessibilityList" type="accessibilityListType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>list of available accessibility types
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="materialReferenceList" type="materialReferenceListType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>list of reference to physical material, could be filenames or an url
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="rightsList" type="rightsListType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>list of rights for this material, each right is for a rights period
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="timestamp" type="xs:dateTime" use="required">
			<xs:annotation>
				<xs:documentation>Timestamp when document is created
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="priceGroupType">
		<xs:annotation>
			<xs:documentation>Tag identifying the priceGroup of the material
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="\w+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="videoFormatType">
		<xs:simpleContent>
			<xs:extension base="videoFormatTypeType">
				<xs:attribute name="threeD" type="xs:boolean">
					<xs:annotation>
						<xs:documentation>Sets to true if video is in 3D or not.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="videoFormatTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="576i" />
			<xs:enumeration value="720p" />
			<xs:enumeration value="1080i" />
			<xs:enumeration value="1080p" />
			<xs:enumeration value="2160p" />
			<xs:enumeration value="other" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="aspectRatioType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="4:3" />
			<xs:enumeration value="16:9" />
			<xs:enumeration value="2.35:1" /><!-- CinemaScope -->
			<xs:enumeration value="21:9" />
			<xs:enumeration value="other" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="audioListType">
		<xs:sequence>
			<xs:element name="format" type="audioType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>audio format, for example surround
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="audioType">
		<xs:simpleContent>
			<xs:extension base="audioFormatType">
				<xs:attribute name="language" type="xs:language">
					<xs:annotation>
						<xs:documentation>code in ISO 639-1</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="materialTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="program" />
			<xs:enumeration value="trailer" />
			<xs:enumeration value="clip" />
			<xs:enumeration value="ad" />
			<xs:enumeration value="other" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="audioFormatType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="mono" />
			<xs:enumeration value="stereo" />
			<xs:enumeration value="surround" />
			<xs:enumeration value="5.1" />
			<xs:enumeration value="other" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="subtitleListType">
		<xs:sequence>
			<xs:element name="subtitle" type="subtitleType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>reference to a subtitle item, for example a teletext page or a subtitle file
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="subtitleType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="xs:language">
					<xs:annotation>
						<xs:documentation>code in ISO 639-1</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="format" type="subtitleFormatType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="subtitleFormatType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="closed" /><!-- text-tv text -->
			<xs:enumeration value="open" />
			<xs:enumeration value="other" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="accessibilityListType">
		<xs:sequence>
			<xs:element name="accessibilityList" type="accessibilityType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>reference to a accessibility item, for example a hearing impaired subtitle
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="accessibilityType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="language" type="xs:language">
					<xs:annotation>
						<xs:documentation>code in ISO 639-1</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="format" type="accessibilityFormatType" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="accessibilityFormatType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="hearingImpairedSubtitle" /><!-- not used by TV4 -->
			<xs:enumeration value="signLanguageInterpretation" />
			<xs:enumeration value="audioDescription" />
			<xs:enumeration value="spokenSubtitle" /><!-- not used by TV4 -->
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="materialReferenceListType">
		<xs:sequence>
			<xs:element name="reference" type="materialReferenceType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="materialReferenceTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="video" />
			<xs:enumeration value="audio" />
			<xs:enumeration value="subtitle" />
			<xs:enumeration value="graphics" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="materialReferenceType">
		<!-- Om flera segment finns, då behövs ordning anges. Hämtas idag från Media i Louise. -->
		<xs:annotation>
			<xs:documentation>element string value is a id, path or any other reference to the media file.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="materialReferenceTypeType">
					<xs:annotation>
						<xs:documentation>type of reference, for example video or audio.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="duration" use="optional">
					<xs:annotation>
						<xs:documentation>duration in timecode for referenced material, example 00:00:00:00
						</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string" />
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="bitrate" use="optional">
					<xs:annotation>
						<xs:documentation>if applicable, bitrate for the material in bps
						</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string" />
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="rightsListType">
		<xs:sequence>
			<xs:element name="rights" type="rightsType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="rightsType">
		<xs:annotation>
			<xs:documentation>DateTime in UTC</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="rightsName" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation> Name of right, i e 'Free' or 'Premium'
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="validFrom" type="xs:dateTime" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Start of period where right is valid
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="validTo" type="xs:dateTime" minOccurs="0">
				<xs:annotation>
					<xs:documentation>End of period where right is valid
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<!-- 
			<xs:element name="unlimitedPeriod" type="xs:boolean" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Indicates if there is a period or not. If true, the rightsCategory is valid until otherwise said
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			-->
			<xs:element name="rightsCategoryList" type="rightsCategoryListType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>list of right categories</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="rightsCategoryListType">
		<xs:sequence>
			<xs:element name="rightsCategory" type="rightsCategoryType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="rightsCategoryType">
		<xs:sequence>
			<!-- not needed, implicit from a publish! 
			Ersätt med list på devicer som för sända denna material 
			<xs:element name="vod" type="deviceTypeRights" minOccurs="0"></xs:element>
			-->
			<!-- ppv = TVOD. Vad är skillnad mot PricceGroup  ??? 
			<xs:element name="ppv" type="deviceTypeRights" minOccurs="0"></xs:element>
			-->
			<xs:element name="devices" type="deviceTypeRights" minOccurs="0">
				<xs:annotation>
					<xs:documentation>list of devices affected by the right</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="timeshift" type="timeShiftDeviceTypeRights" minOccurs="0"></xs:element>
			<xs:element name="noLinearTransmission" type="transmissionDeviceTypeRights" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Linear transmision may not be sent to these devices.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="addProviderLogo" type="xs:boolean" default="true" />
			<xs:element name="allowAds" type="xs:boolean" default="true" />
			<xs:element name="drmRestrictions" type="drmRestrictionsType" minOccurs="0" />
			<xs:element name="geoRestrictions" type="geoRestrictionsType" minOccurs="0" />
			<xs:element name="shareToList">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="shareTo" type="shareToType" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>youtube, facebook, twitter, ... (should/could be tags?)</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="drmRestrictionsType">
		<xs:sequence></xs:sequence>
	</xs:complexType>
	<xs:complexType name="geoRestrictionsType">
		<xs:sequence></xs:sequence>
	</xs:complexType>
	<xs:complexType name="timeShiftDeviceTypeRights">
		<xs:sequence>
			<xs:element name="catchUpRights" type="catchUpRightsType" minOccurs="0" maxOccurs="1">
			</xs:element>
			<xs:element name="startOverRights" type="startOverRightsType" minOccurs="0" maxOccurs="1">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="transmissionDeviceTypeRights">
		<xs:complexContent>
			<xs:extension base="deviceTypeRights">
				<xs:annotation>
					<xs:documentation>Can be used in example for marking a tv-show in the schedule that aren't allowed to be transmitted to mobile clients
					</xs:documentation>
				</xs:annotation>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="deviceTypeRights">
		<xs:sequence>
			<xs:element name="deviceType" type="deviceTypeType" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="deviceTypeOutPutRights">
		<xs:complexContent>
			<xs:extension base="deviceTypeRights">
				<xs:sequence>
					<xs:element name="digitalOutputRights" type="digitalOutputRightsType" minOccurs="0">
					</xs:element>
					<xs:element name="analogOutputRights" type="analogOutputRightsType" minOccurs="0">
					</xs:element>
					<xs:element name="inHomeNetworkOutputRights" type="inHomeNetworkOutputRightsType" minOccurs="0">
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="deviceTypeType">
		<xs:annotation>
			<xs:documentation>Controls the device type
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="web" />
			<xs:enumeration value="mob" />
			<xs:enumeration value="tab" />
			<xs:enumeration value="stb" />
			<xs:enumeration value="ott" />
			<xs:enumeration value="console" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="digitalOutputRightsType">
		<xs:annotation>
			<xs:documentation>Controls the output source for digital sources
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="unrestricted" />
			<xs:enumeration value="besteffort" />
			<xs:enumeration value="restricted" />
			<xs:enumeration value="disallow" />
			<xs:enumeration value="downresolution" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="analogOutputRightsType">
		<xs:choice>
			<xs:element name="unrestricted" type="xs:boolean"></xs:element>
			<xs:element name="besteffort" type="cgmsaType"></xs:element>
			<xs:element name="restricted" type="cgmsaType"></xs:element>
			<xs:element name="disallow" type="xs:boolean">
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="cgmsaType">
		<xs:annotation>
			<xs:documentation>CGMS-A is standardized through the IEC, CEA, EIA-J and ETS
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="copyfreely" />
			<xs:enumeration value="copynomore" />
			<xs:enumeration value="copyonce" />
			<xs:enumeration value="copynever" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="inHomeNetworkOutputRightsType">
		<xs:annotation>
			<xs:documentation>Controls the output source for network services
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="unrestricted" />
			<xs:enumeration value="disallow" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="deviceTypeListType">
		<xs:sequence>
			<xs:element name="deviceTypeList" type="deviceTypeRights" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="catchUpRightsType">
		<xs:sequence>
			<xs:element name="fastForward" type="xs:boolean" minOccurs="0"></xs:element>
			<xs:element name="rewind" type="xs:boolean" minOccurs="0">
			</xs:element>
			<xs:element name="pause" type="xs:boolean" minOccurs="0">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="startOverRightsType">
		<xs:sequence>
			<xs:element name="fastForward" type="xs:boolean" minOccurs="0"></xs:element>
			<xs:element name="rewind" type="xs:boolean" minOccurs="0">
			</xs:element>
			<xs:element name="pause" type="xs:boolean" minOccurs="0">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="shareToType">
		<!-- TODO : borde ange om det är en exclusive or excluding right -->
		<xs:annotation>
			<xs:documentation>Tag identifying the channel that is allowed for sharing. '*' to indicate all and anyware.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(\*)|(\w+)"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="materialListType">
		<xs:sequence>
			<xs:element name="material" type="materialType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== JohanSpaedtke/video-metadata-api/src/main/xml/material.xml
<?xml version="1.0" encoding="UTF-8"?>
<material:material timestamp="2001-12-31T12:00:00" xmlns:common="http://video-metadata.tv.se/common/v1" xmlns:material="http://video-metadata.tv.se/material/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://video-metadata.tv.se/material/v1 ../xsd/material.xsd ">
  <providerId>providerId</providerId>
  <id>1234567890</id>
  <distributor>se.tv4</distributor>
  <priceGroup>Premium</priceGroup>
  <contentIdRef>contentIdRef</contentIdRef>
  <materialType>program</materialType>
  <videoFormat threeD="true">576i</videoFormat>
  <audioList>
    <format language="EN">mono</format>
  </audioList>
  <aspectRatio>4:3</aspectRatio>
  <subtitleList>
    <subtitle format="closed" language="EN">subtitle</subtitle>
  </subtitleList>
  <accessibilityList>
    <accessibilityList format="hearingImpairedSubtitle" language="EN">accessibilityList</accessibilityList>
  </accessibilityList>
  <materialReferenceList>
    <reference bitrate="" duration="" type="video">reference</reference>
  </materialReferenceList>
  <rightsList>
    <rights>
      <rightsName>rightsName</rightsName>
      <validFrom>2001-12-31T12:00:00</validFrom>
      <validTo>2001-12-31T12:00:00</validTo>
      <unlimitedPeriod>true</unlimitedPeriod>
      <rightsCategoryList>
        <rightsCategory>
          <vod xsi:type="material:deviceTypeRights">
            <deviceType>web</deviceType>
          </vod>
          <ppv xsi:type="material:deviceTypeRights">
            <deviceType>web</deviceType>
          </ppv>
          <timeshift>
            <catchUpRights>
              <fastForward>true</fastForward>
              <rewind>true</rewind>
              <pause>true</pause>
            </catchUpRights>
            <startOverRights>
              <fastForward>true</fastForward>
              <rewind>true</rewind>
              <pause>true</pause>
            </startOverRights>
          </timeshift>
          <noTransmission>
            <deviceType>web</deviceType>
          </noTransmission>
          <addProviderLogo>true</addProviderLogo>
          <allowAds>true</allowAds>
          <drmRestrictions/>
          <geoRestrictions/>
          <shareToList>
            <shareTo>shareTo</shareTo>
          </shareToList>
        </rightsCategory>
      </rightsCategoryList>
    </rights>
  </rightsList>
</material:material>
